[persistence]
data-path="/opt/maru/data"
private-key-path="/opt/maru/private-key"

[p2p]
port = 21010
ip-address = "0.0.0.0"
static-peers = [
  "/ip4/18.223.198.165/tcp/31005/p2p/16Uiu2HAmSJSpgBxVoMcRZ4u8CQbTgfPrbw6u7xH1BnMgwAQZAm91",
  "/ip4/18.190.136.59/tcp/31006/p2p/16Uiu2HAm5DpcTYVLzZf45unDDrY9wYVbqeFnPo4CrpnF3tyXV3o8",
  "/ip4/13.50.94.193/tcp/31003/p2p/16Uiu2HAmVcX8oB9KxmJdVAGybMyxuqtbY959i6uaew1agDBv9wk3",
  "/ip4/3.1.142.64/tcp/31000/p2p/16Uiu2HAkuaxfz8ftqSSfG6hKG7B7MCUD9boXvawxKXz9eq7R6Tmi",
  "/ip4/52.77.66.99/tcp/31001/p2p/16Uiu2HAmGNP9fqUnfCb5v8VAWczW12qmsEnYhNUw2v652Px9Kz5V"
]
reconnect-delay = "500 ms"

[p2p.discovery]
port = 21010
bootnodes = []
refresh-interval = "10s"

[payload-validator]
engine-api-endpoint = { endpoint = "http://el-client:8551", jwt-secret-path = "/opt/jwt/jwt.hex" }
payload-validation-enabled = false

[observability]
port = 9090
jvm-metrics-enabled = false
prometheus-metrics-enabled = false

[api]
port = 21011

[syncing]
peer-chain-height-polling-interval = "5 seconds"
el-sync-status-refresh-interval = "5 seconds"
sync-target-selection = "Highest"
desync-tolerance = 10

[syncing.download]
block-range-request-timeout = "10 seconds"
blocks-batch-size = 10
blocks-parallelism = 10
max-retries = 5
backoff-delay = "1 seconds"
use-unconditional-random-download-peer = false
