[persistence]
data-path="/opt/maru/data"
private-key-path="/opt/maru/private-key"

[p2p]
port = 21110
ip-address = "0.0.0.0"
static-peers = [
  "/ip4/3.129.120.128/tcp/31005/p2p/16Uiu2HAmR33t8RZiAHovuH9iH2UuUrajrbfyYowiYDAQo3D5Y9wg",
  "/ip4/3.129.120.128/tcp/31006/p2p/16Uiu2HAm9HB5oNmnmj8yY6T7dfhLVidVzYqa8QVDtEthkMr6b8tx"
]
reconnect-delay = "500 ms"

[p2p.discovery]
port = 21110
bootnodes = []
refresh-interval = "10s"

[payload-validator]
engine-api-endpoint = { endpoint = "http://el-client:8551", jwt-secret-path = "/opt/jwt/jwt.hex" }
payload-validation-enabled = false

[observability]
port = 9090
jvm-metrics-enabled = false
prometheus-metrics-enabled = false

[api]
port = 21111

[syncing]
peer-chain-height-polling-interval = "5 seconds"
el-sync-status-refresh-interval = "5 seconds"
sync-target-selection = "Highest"
desync-tolerance = 10

[syncing.download]
block-range-request-timeout = "10 seconds"
blocks-batch-size = 10
blocks-parallelism = 10
max-retries = 5
backoff-delay = "1 seconds"
use-unconditional-random-download-peer = false
